database:
  dbname: railway
  user: postgres
  password: JDLyqKJVxfGtzlCoBKdiadUbMAdrBFdZ
  host: switchback.proxy.rlwy.net
  port: 24684

check_tables: true

https_only: false
external_port: 3000

# Enable these if needed
feed_menu: true
registration_enabled: false
captcha_enabled: false

# Performance settings
popular_enabled: true
popular_sort: "one_week"

# Logging
log_level: info
log_file: /var/log/invidious.log
